@Library('easyToBuy-Jenkins_SharedLib') _

pipeline {
  agent any
   parameters{

          string(name: 'ImageName', description: "Name of Docker Build", defaultValue: 'user-service')
          string(name: 'ImageTag', description: "Tag for Docker Build", defaultValue: 'v1')
          string(name: 'DockerHubUser', description: "Name of the Service", defaultValue: 'satishlakshmiudemy')
      }
  stages {
    stage('Git Checkout') {
      steps {
        gitCheckout([$class: 'GitSCM',
          branch: "master",
          url: "https://github.com/MaruthamSatishReddy/EASY-TO-BUY-V2.git"
        ])
      }
    }
  stage('Maven Unit Test') {
      steps {
        dir('USER-SERVICE') {
          mavenTest()
        }
      }
    }
    stage('Maven Integration Test') {
      steps {
        dir('USER-SERVICE') {
          mavenIntegrationTest()
        }
      }
    }
    stage('Code Analysis: SonarQube') {
      steps {
        dir('USER-SERVICE') {
          staticCodeAnalysis('SonarQube')
        }
      }
    }
    stage('Maven Build') {
          steps {
            dir('USER-SERVICE') {
              mavenBuild()
            }
          }
        }
    stage('Docker Image Build') {
              steps {
                dir('USER-SERVICE') {
                  dockerImageBuild("${params.ImageName}","${params.ImageTag}","${params.DockerHubUser}")
                }
              }
            }
  }
}